spring.application.name=Linkster
server.port=8080


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/linksterdb
spring.datasource.username=shamil
spring.datasource.password=Shoma1996
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# Logging Configuration
logging.level.hibernate.SQL=debug
logging.level.hibernate.orm.jdbc.bind=trace

